---
title: "TIE"
format: html
embeded-resources: true
execute:
  echo: true
  warning: false
editor: 
  markdown: 
    wrap: 72
---
```{r, echo=FALSE, include=FALSE, message=FALSE, warning=FALSE}
options(repos = c(CRAN = "https://cloud.r-project.org"))
options(scipen = 999)

library(dplyr)
library(ggplot2)
library(rstudioapi)
library(tidyr)
library(knitr)
library(kableExtra)
library(readr)
library(gridExtra)
library(lubridate)
library(readxl)
library(xfun)
library(rmarkdown)
library(scales)
```
# International Capital Flows
```{r, echo=FALSE, include=FALSE, message=FALSE, warning=FALSE}
fdi_inflow <- read_excel("fdi_inflows_WIR2024_tab01.xlsx")
```
```{r, echo=FALSE, include=FALSE, message=FALSE, warning=FALSE}
colnames(fdi_inflow) <- c("Region/Economy", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023")
fdi_inflow <- fdi_inflow[fdi_inflow$"Region/Economy" %in% c("Austria",
                                                               "Belgium",
                                                               "Denmark",
                                                               "Finland",
                                                               "France",
                                                               "Germany",
                                                               "Greece",
                                                               "Ireland",
                                                               "Italy",
                                                               "Luxembourg",
                                                               "Netherlands",
                                                               "Portugal",
                                                               "Spain",
                                                               "Sweden",
                                                               "United Kingdom",
                                                               "European Union"),]
```
```{r, echo=FALSE, include=FALSE, message=FALSE, warning=FALSE}
fdi_outflow <- read_excel("fdi_outflows_WIR2024_tab02.xlsx")
```
```{r, echo=FALSE, include=FALSE, message=FALSE, warning=FALSE}
colnames(fdi_outflow) <- c("Region/Economy", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023")
fdi_outflow <- fdi_outflow[fdi_outflow$"Region/Economy" %in% c("Austria",
                                                               "Belgium",
                                                               "Denmark",
                                                               "Finland",
                                                               "France",
                                                               "Germany",
                                                               "Greece",
                                                               "Ireland",
                                                               "Italy",
                                                               "Luxembourg",
                                                               "Netherlands",
                                                               "Portugal",
                                                               "Spain",
                                                               "Sweden",
                                                               "United Kingdom",
                                                               "European Union"),]
```
```{r, echo=FALSE, include=FALSE, message=FALSE, warning=FALSE}
fdi_merged <- merge(fdi_inflow, fdi_outflow, by = "Region/Economy")
cols_x <- grep("\\.x$", names(fdi_merged), value = TRUE)
for (col in cols_x) {
  base_name <- sub("\\.x$", "", col)
  fdi_merged[[base_name]] <- fdi_merged[[col]] - fdi_merged[[paste0(base_name, ".y")]]
}
fdi_net_balance <- fdi_merged|>
  select(-matches("\\.x$|\\.y$"))
```
```{r, echo=FALSE}
fdi_balance_long <- fdi_net_balance|>
  filter(`Region/Economy` != "European Union")|>
  pivot_longer(
    cols = matches("^\\d{4}$"),
    names_to = "Year",
    values_to = "FDI"
  )|>
  mutate(Year = as.numeric(Year)) %>%
  filter(Year >= 1995)

fdi_balance_avg <- fdi_balance_long|>
  group_by(Year)|>
  summarize(FDI = mean(FDI, na.rm = TRUE))

ggplot(
  fdi_net_balance|>
    filter(`Region/Economy` != "European Union") %>%
    pivot_longer(
      cols = matches("^\\d{4}$"),
      names_to = "Year",
      values_to = "FDI")|>
    mutate(Year = as.numeric(Year))|>
    filter(Year >= 1995),
  aes(x = Year, y = FDI, color = `Region/Economy`, group = `Region/Economy`))+
  geom_line()+
  geom_line(data = fdi_balance_avg, aes(x = Year, y = FDI), 
            color = "red", size = 0.7, inherit.aes = FALSE) +
  geom_vline(xintercept = c(2004.33, 2007.00, 2013.5, 2020.08), 
             linetype = "dashed", color = "red")+
  labs(
    title = "Foreign Direct Investment Net Balance",
    x = NULL,
    y = "FDI (in millions USD)",
    color = "Country")+
  scale_y_continuous(labels = function(x) format(x, big.mark = ",", scientific = FALSE))+
  theme_minimal()+
  theme(
    legend.position = "bottom",
    plot.title = element_text(hjust = 0.5, face = "bold"))
```
```{r, echo=FALSE, message=FALSE, warning=FALSE}
fdi_balance_long <- fdi_net_balance |>
  filter(`Region/Economy` != "European Union") |>
  pivot_longer(
    cols = matches("^\\d{4}$"),
    names_to = "Year",
    values_to = "FDI"
  ) |>
  mutate(Year = as.numeric(Year)) |>
  filter(Year >= 1995)
fdi_balance_avg <- fdi_balance_long |>
  group_by(Year) |>
  summarise(FDI = mean(FDI, na.rm = TRUE), .groups = "drop")

ggplot(fdi_balance_avg, aes(x = Year, y = FDI)) +
  geom_line(color = "red", size = 1) +
  labs(
    title = "Average Net Foreign Direct Investment (FDI)",
    x = NULL,
    y = "FDI (in millions USD)")+
  scale_y_continuous(labels = scales::comma) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"))

ggsave("fdi_avg_plot.pdf", width = 8, height = 5, units = "in", dpi = 300)
```
# International Labor Flows
```{r, echo=FALSE, message=FALSE, warning=FALSE}
labor_flow <- read_csv("MST_XWAP_SEX_AGE_CBR_NB_A-20250516T1047.csv")
```
```{r, echo=FALSE, message=FALSE, warning=FALSE}
labor_flow <- labor_flow[labor_flow$"ref_area.label" %in% c("Austria",
                                                               "Belgium",
                                                               "Denmark",
                                                               "Finland",
                                                               "France",
                                                               "Germany",
                                                               "Greece",
                                                               "Ireland",
                                                               "Italy",
                                                               "Luxembourg",
                                                               "Netherlands",
                                                               "Portugal",
                                                               "Spain",
                                                               "Sweden",
                                                               "United Kingdom of Great Britain and Northern Ireland",
                                                               "European Union"),]

labor_flow_filtered <- labor_flow|>
  filter(classif1.label == "Age (Youth, adults): 15-64", sex.label == "Total")
```
```{r, echo=FALSE, message=FALSE, warning=FALSE}
ratio_migrant_workers <- labor_flow_filtered|>
  filter(classif2.label %in% c("Place of birth: Foreign-born", "Place of birth: Native-born"))

wide_data <- ratio_migrant_workers|>
  pivot_wider(names_from = classif2.label, values_from = obs_value)
wide_data <- wide_data|>
  mutate(ratio = as.numeric(`Place of birth: Foreign-born`) / as.numeric(`Place of birth: Native-born`))
wide_data <- wide_data|>
  mutate(ratio = scales::label_number(accuracy = 0.0001)(ratio))
wide_data <- wide_data|>
  mutate(ratio = as.numeric(ratio))

ratio_migrant_workers <- wide_data|>
  group_by(time, ref_area.label)|>
  summarize(ratio = sum(ratio, na.rm = TRUE), .groups = 'drop')
```
```{r, echo=FALSE, message=FALSE, warning=FALSE}
ratio_migrant_workers <- ratio_migrant_workers|>
  complete(ref_area.label, time = 1995:2024, fill = list(ratio = NA))|>
  filter(time >= 1995)

ratio_migrant_workers <- ratio_migrant_workers|>
  mutate(ref_area.label = ifelse(ref_area.label == "United Kingdom of Great Britain and Northern Ireland", 
                                 "United Kingdom", 
                                 ref_area.label))
```
```{r, echo=FALSE}
ggplot(ratio_migrant_workers, aes(x = time, y = ratio, color = ref_area.label))+
  geom_line()+
  geom_vline(xintercept = c(2004, 2007, 2013, 2020), 
             color = "red", linetype = "dashed", size = 0.5)+
  labs(
    title = "Ratio of Migrant Workers (Relative to Native Workers)",
    x = NULL,
    y = "Ratio of Migrant Workers",
    color = "Country")+
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 1),
    legend.position = "right",
    plot.title = element_text(face = "bold", hjust = 0.5))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
ratio_avg <- ratio_migrant_workers |>
  filter(time <= 2023) |>
  group_by(time) |>
  summarise(ratio = mean(ratio, na.rm = TRUE), .groups = "drop")

ggplot(ratio_avg, aes(x = time, y = ratio)) +
  geom_line(color = "red", size = 1) +
  labs(
    title = "Average Ratio of Migrant to Native Workers",
    x = NULL,
    y = "Average Ratio") +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5))

ggsave("migrant_ratio_avg_plot.pdf", width = 8, height = 5, units = "in", dpi = 300)
```
# International Trade
```{r, echo=FALSE, message=FALSE, warning=FALSE}
international_trade_1 <- read_csv("international_trade/1995-2004_TradeData_5_16_2025_17_52_30.csv")
international_trade_2 <- read_csv("international_trade/2005-2014_TradeData_5_16_2025_17_53_56.csv")
international_trade_3 <- read_csv("international_trade/2015-2024_TradeData_5_16_2025_17_55_3.csv")
View(international_trade_1)
View(international_trade_2)
View(international_trade_3)
```
```{r, echo=FALSE, message=FALSE, warning=FALSE}
international_trade <- bind_rows(international_trade_1, international_trade_2, international_trade_3)
international_trade <- international_trade|>
  filter(reporterDesc %in% c("Austria",
                             "Belgium",
                             "Belgium-Luxembourg (...1998)",
                             "Denmark",
                             "Finland",
                             "France",
                             "Germany",
                             "Greece",
                             "Ireland",
                             "Italy",
                             "Luxembourg",
                             "Netherlands",
                             "Portugal",
                             "Spain",
                             "Sweden",
                             "United Kingdom"))
```
```{r, echo=FALSE}
trade_balance <- international_trade|>
  filter(period >= 1995, period <= 2023)|>
  group_by(reporterDesc, period)|>
  summarize(
    fobvalue_sum = sum(fobvalue, na.rm = TRUE),
    cifvalue_sum = sum(cifvalue, na.rm = TRUE),
    .groups = "drop")|>
  mutate(balance_difference = fobvalue_sum - cifvalue_sum)|>
  select(reporterDesc, period, balance_difference)
```
```{r, echo=FALSE}
ggplot(trade_balance, aes(x = period, y = balance_difference, color = reporterDesc, group = reporterDesc)) +
  geom_line() +
  geom_point(size = 0.5) +
  geom_vline(xintercept = 2004 + 4/12, linetype = "dotted", color = "red") +
  geom_vline(xintercept = 2007, linetype = "dotted", color = "red") +
  geom_vline(xintercept = 2013 + 6/12, linetype = "dotted", color = "red") +
  geom_vline(xintercept = 2020 + 0.08, linetype = "dotted", color = "red") +
  geom_hline(aes(yintercept = mean(balance_difference, na.rm = TRUE)),
             color = "red", size = 0.7) +
  scale_y_continuous(labels = function(x) format(x, big.mark = ",", scientific = FALSE)) +
  labs(
    title = "Trade Balance of Goods",
    x = NULL,
    y = "Trade balance of Goods (in USD)",
    color = "Country")+
  theme_minimal()+
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"))
```
```{r, echo=FALSE}
trade_balance_avg <- trade_balance |>
  filter(period <= 2023) |>
  group_by(period) |>
  summarise(balance_difference = mean(balance_difference, na.rm = TRUE), .groups = "drop") |>
  mutate(balance_difference = balance_difference / 1e6)

ggplot(trade_balance_avg, aes(x = period, y = balance_difference)) +
  geom_line(color = "red", size = 1) +
  scale_y_continuous(
    labels = function(x) paste0(format(x, big.mark = ","))) +
  labs(
    title = "Average Trade Balance of Goods",
    x = NULL,
    y = "Trade Balance of Goods (in millions USD)") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"))

ggsave("trade_avg_plot.pdf", width = 8, height = 5, units = "in", dpi = 300)
```
```{r, echo=FALSE, message=FALSE, warning=FALSE}
fdi_net_balance <- fdi_net_balance|>
  pivot_longer(cols = -"Region/Economy",
               names_to = "Year",
               values_to = "FDInet")
```
```{r, echo=FALSE, message=FALSE, warning=FALSE}
colnames(fdi_net_balance)[colnames(fdi_net_balance) == "Region/Economy"] <- "Economy"

colnames(trade_balance)[colnames(trade_balance) == "reporterDesc"] <- "Economy"
colnames(trade_balance)[colnames(trade_balance) == "period"] <- "Year"
colnames(trade_balance)[colnames(trade_balance) == "balance_difference"] <- "X-M"

colnames(ratio_migrant_workers)[colnames(ratio_migrant_workers) == "ref_area.label"] <- "Economy"
colnames(ratio_migrant_workers)[colnames(ratio_migrant_workers) == "time"] <- "Year"
colnames(ratio_migrant_workers)[colnames(ratio_migrant_workers) == "ratio"] <- "MWr"

trade_balance_filtered <- trade_balance|> filter(Economy != "Belgium-Luxembourg (...1998)")
fdi_net_balance_filtered <- fdi_net_balance|> filter(Economy != "European Union")

trade_balance_filtered$Year <- as.numeric(trade_balance_filtered$Year)
fdi_net_balance_filtered$Year <- as.numeric(fdi_net_balance_filtered$Year)
ratio_migrant_workers$Year <- as.numeric(ratio_migrant_workers$Year)

Globalization <- merge(trade_balance_filtered, fdi_net_balance_filtered, by = c("Economy", "Year"), all = TRUE)
Globalization <- merge(Globalization, ratio_migrant_workers, by = c("Economy", "Year"), all = TRUE)

Globalization <- Globalization|>
  filter(Year >= 1995 & Year <= 2023)
```
```{r, echo=FALSE}
names(Globalization)[names(Globalization) == "X-M"] <- "Trade balance of goods"
names(Globalization)[names(Globalization) == "FDInet"] <- "FDI net balance"
names(Globalization)[names(Globalization) == "MWr"] <- "Ratio of migrant to native workers"

summary_table <- Globalization[,c(3:5)]

summary_table$`Trade balance of goods` <- summary_table$`Trade balance of goods` / 1e6

summary_table <- data.frame(
  N = sapply(summary_table, function(x) sum(!is.na(x))),
  Min = sapply(summary_table, function(x) if(is.numeric(x)) min(x, na.rm = TRUE) else NA),
  Max = sapply(summary_table, function(x) if(is.numeric(x)) max(x, na.rm = TRUE) else NA),
  Mean = sapply(summary_table, function(x) if(is.numeric(x)) mean(x, na.rm = TRUE) else NA),
  Median = sapply(summary_table, function(x) if(is.numeric(x)) median(x, na.rm = TRUE) else NA),
  NAs = sapply(summary_table, function(x) sum(is.na(x))))

summary_table$Mean <- round(summary_table$Mean, 2)
summary_table$Median <- round(summary_table$Median, 2)

kable(summary_table, format = "html", table.attr = "class='table table-striped'",
      caption = "<b>Preliminary Descriptive Statistics of Globalisation Data</b>")|>
  kable_styling(
    bootstrap_options = c("striped", "hover"),
    font_size = 14,
    position = "center",
    full_width = FALSE)|>
  footnote(
    general = "Values for trade balance of goods and net foreign direct investment
    are expressed in millions of USD.",
    footnote_as_chunk = TRUE)
  
```
```{r, echo=FALSE}
unique(Globalization$Economy)

Globalization <- Globalization %>%
  mutate(Economy = recode(Economy,
    "Austria" = "AT",
    "Belgium" = "BE",
    "Denmark" = "DK",
    "Finland" = "FI",
    "France" = "FR",
    "Germany" = "DE",
    "Greece" = "GR",
    "Ireland" = "IE",
    "Italy" = "IT",
    "Luxembourg" = "LU",
    "Netherlands" = "NL",
    "Portugal" = "PT",
    "Spain" = "ES",
    "Sweden" = "SE",
    "United Kingdom" = "UK"
  ))

Globalization <- Globalization[order(Globalization$Year, Globalization$Economy),]
Globalization$`Trade balance of goods` <- Globalization$`Trade balance of goods` / 1e6
```

```{r, echo=FALSE}
Globalization[Globalization == 0.0]<-NA
```
```{r, echo=FALSE}
DE_MWr <- read_csv("DE_MWr_12411-0007.csv")

DE_MWr_sum <- DE_MWr|>
  group_by(Year)|>
  summarize(across(c("Germans M", "Germans F", "Foreigners M", "Foreigners F"), sum, na.rm = TRUE))

DE_MWr_sum <- DE_MWr|>
  group_by(Year)|>
  summarize(
    Germans = sum(`Germans M` + `Germans F`, na.rm = TRUE),
    Foreigners = sum(`Foreigners M` + `Foreigners F`, na.rm = TRUE))

DE_MWr <- DE_MWr_sum|>
  mutate(`Ratio of migrant to native workers` = Foreigners / Germans)

DE_MWr <- DE_MWr|>
mutate(`Ratio of migrant to native workers` = round(`Ratio of migrant to native workers`, 4))

DE_MWr <- DE_MWr|>
  mutate(Economy = "DE")

DE_MWr <- DE_MWr|>
  select(-`Germans`, -`Foreigners`)

Globalization_actualized <- Globalization|>
  left_join(
    DE_MWr|> select(Year, Economy, `Ratio of migrant to native workers`),
    by = c("Year", "Economy"),
    suffix = c("", ".new")
  )|>
  mutate(
    `Ratio of migrant to native workers` = coalesce(`Ratio of migrant to native workers.new`, `Ratio of migrant to native workers`)
  )|>
  select(-`Ratio of migrant to native workers.new`)
```
```{r, echo=FALSE}
laborforce <- read_csv("ILOSTAT_laborforce_MST_TEAP_SEX_AGE_CCT_NB_A-20250611T0918.csv")
names(laborforce)[1] <- "Economy"

laborforce_filtered <- laborforce %>%
  filter(
    (Economy == "Italy" & time %in% 1995:2004) |
    (Economy == "Greece" & time == 2005) |
    (Economy == "Finland" & time == 1995) |
    (Economy == "Ireland" & time %in% 1995:1997)
  )
laborforce_filtered <- laborforce_filtered%>%
  filter(
    sex.label == "Total",
    classif2.label %in% c("Citizenship: National citizens", "Citizenship: Foreign citizens"),
    classif1.label == "Age (Youth, adults): 15-24"
  )

laborforce_filtered <- laborforce_filtered %>%
  select(Economy, time, classif2.label, obs_value) %>%
  pivot_wider(
    names_from = classif2.label,
    values_from = obs_value
  ) %>%
  mutate(
    ratio_foreign_to_national = `Citizenship: Foreign citizens` / `Citizenship: National citizens`
  ) %>%
  select(Economy, time, ratio_foreign_to_national)

laborforce_greece <- laborforce_filtered %>%
  filter(Economy == "Greece")

laborforce_greece <- laborforce_greece %>%
  rename(
    Year = 2,
    `Ratio of migrant to native workers` = 3
  )
laborforce_greece <- laborforce_greece|>
mutate(`Ratio of migrant to native workers` = round(`Ratio of migrant to native workers`, 4))

laborforce_greece <- laborforce_greece %>%
  mutate(Economy = ifelse(Economy == "Greece", "GR", Economy))

Globalization_actualized <- Globalization_actualized|>
  left_join(
    laborforce_greece|> select(Year, Economy, `Ratio of migrant to native workers`),
    by = c("Year", "Economy"),
    suffix = c("", ".new")
  )|>
  mutate(
    `Ratio of migrant to native workers` = coalesce(`Ratio of migrant to native workers.new`, `Ratio of migrant to native workers`)
  )|>
  select(-`Ratio of migrant to native workers.new`)
```
```{r, echo=FALSE}
trade_merch_balance <- read_csv("US_TradeMerchBalance.csv.7z")

trade_merch_filtered <- trade_merch_balance|>
  filter(
    `Economy Label` %in% c("Belgium", "Luxembourg"),
    Year %in% 1995:2001
  )
colnames(trade_merch_filtered)
trade_merch_filtered <- trade_merch_filtered %>%
  select(Year, `Economy Label`, `US$ at current prices in millions`)

trade_merch_filtered <- trade_merch_filtered %>%
  rename(
    Economy = `Economy Label`,
    `Trade balance of goods` = `US$ at current prices in millions`
  )
trade_merch_filtered <- trade_merch_filtered %>%
  mutate(Economy = case_when(
    Economy == "Belgium" ~ "BE",
    Economy == "Luxembourg" ~ "LU",
    TRUE ~ Economy
  ))

Globalization_actualized <- Globalization_actualized %>%
  left_join(
    trade_merch_filtered %>% select(Year, Economy, `Trade balance of goods`) %>%
      rename(`Trade balance of goods.new` = `Trade balance of goods`),
    by = c("Year", "Economy")
  ) %>%
  mutate(`Trade balance of goods` = coalesce(`Trade balance of goods.new`, `Trade balance of goods`)) %>%
  select(-`Trade balance of goods.new`)
```
```{r, echo=FALSE}
Globalization_actualized <- Globalization_actualized %>%
  rename(Country = Economy)
```
```{r, echo=FALSE}
write.csv(Globalization_actualized, "globalization.csv", row.names = FALSE)
```